---
- name: Create Ubuntu and Windows VM
  hosts: localhost
  connection: local
  vars_prompt:
    - name: az_admin_pass
      prompt: please enter admin password for Windows VM
  tasks:
  - name: Include vars file
    include_vars:
      file: vars.yml
  - name: Create '{{az_resourcegroup}}'
    azure_rm_resourcegroup:
      name: '{{az_resourcegroup}}'
      location: '{{az_location}}'
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: '{{az_resourcegroup}}'
      name: myVnet
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: '{{az_resourcegroup}}'
      name: mySubnet
      address_prefix: "10.0.1.0/24"
      virtual_network: myVnet
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: '{{az_resourcegroup}}'
      allocation_method: Static
      name: myPublicIP
    register: output_ip_address
  - name: Dump public IP for VM which will be created
    debug:
      msg: "The public IP for ubuntu server is {{ output_ip_address.state.ip_address }}."
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: '{{az_resourcegroup}}'
      name: myNetworkSecurityGroup
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
  - name: Create virtual network interface card
    azure_rm_networkinterface:
      resource_group: '{{az_resourcegroup}}'
      name: myNIC
      virtual_network: myVnet
      subnet: mySubnet
      public_ip_name: myPublicIP
      security_group: myNetworkSecurityGroup
  - name: Create Ubuntu VM
    azure_rm_virtualmachine:
      resource_group: '{{az_resourcegroup}}'
      name: ubuntu01
      vm_size: Standard_DS1_v2
      admin_username: azureuser
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/azureuser/.ssh/authorized_keys
          key_data: '{{key_data}}'
      network_interfaces: myNIC
      image:
        offer: UbuntuServer
        publisher: Canonical
        sku: '18.04-LTS'
        version: latest
  - name: Create Windows VM
    azure_rm_virtualmachine:
      resource_group: '{{az_resourcegroup}}'
      name: winserver01
      vm_size: Standard_DS1_v2
      admin_username: '{{azure_adminuser}}'
      admin_password: '{{az_admin_pass}}'
      os_type: Windows
      image:
        offer: WindowsServer
        publisher: MicrosoftWindowsServer
        sku: 2019-Datacenter
        version: latest