---
- name: Prepare CentOS 7.5 machine for AWX Install
  hosts: centos01
  become: yes
  
  tasks:
  
  - name: stop and disable firewalld
    service:
      name: firewalld
      state: stopped
      enabled: no
      
  - name: edit /etc/sysconfig/selinux
    copy:
      dest: /etc/sysconfig/selinux
      content:
        SELINUX=disabled

  - name: reboot
    reboot:

  - name: install epel-release
    yum:
      name: epel-release

  - name: yum update
    yum:
      name: '*'
      state: latest

  - name: add repo https://download.docker.com/linux/centos/docker-ce.repo
    shell:
      wget https://download.docker.com/linux/centos/docker-ce.repo --directory-prefix /etc/yum.repos.d/
  
  - name: install git gcc gcc-c++ ansible nodejs gettext device-mapper-persistent-data lvm2 bzip2 python3-pip python-docker wget nano python3-devel docker-ce
    yum:
      name: "{{ packages }}"
    vars:
      packages:
        - git
        - gcc 
        - gcc-c++ 
        - ansible
        - nodejs
        - gettext
        - device-mapper-persistent-data
        - lvm2
        - bzip2
        - python3-pip
        - python-docker
        - wget 
        - nano 
        - python3-devel
        - docker-ce

  - name: start and enable docker service
    service:
      name: docker
      state: started
      enabled: yes

  - name: pip3 install docker-compose
    pip:
         name:
           - docker-compose
           - selinux
         executable: pip3

  - name: sudo usermod -aG docker $USER
    user:
       name: "{{ansible_user}}"
       groups: docker
       append: true

  - name: git clone https://github.com/ansible/awx.git
    git:
      repo: https://github.com/ansible/awx.git
      dest: /awx