---
- name: Create CentOS VM
  hosts: localhost
  connection: local

  tasks:
  
  - name: Create CentOS VM
    azure_rm_virtualmachine:
      resource_group: '{{az_resourcegroup}}'
      name: centos01
      vm_size: Standard_B2s
      admin_username: azureuser
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/azureuser/.ssh/authorized_keys
          key_data: '{{key_data}}'
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.5'
        version: latest
