---
- name: Create Az NSG
  hosts: localhost
  connection: local

  tasks:
  
  - name: Create Network Security Group that allows SSH and HTTP
    azure_rm_securitygroup:
      resource_group: '{{az_resourcegroup}}'
      name: '{{az_nsg}}'
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
        - name: http
          protocol: Tcp
          destination_port_range: 80
          access: Allow
          priority: 1002
          direction: Inbound