---
- name: Create Ubuntu and Windows VM
  hosts: localhost
  connection: local

  tasks:
 
  - name: Create Ubuntu VM
    azure_rm_virtualmachine:
      resource_group: '{{az_resourcegroup}}'
      name: ubuntu01
      vm_size: Standard_DS1_v2
      admin_username: azureuser
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/azureuser/.ssh/authorized_keys
          key_data: '{{key_data}}'
      image:
        offer: UbuntuServer
        publisher: Canonical
        sku: '18.04-LTS'
        version: latest