---
- name: Create CentOS VM
  hosts: localhost
  connection: local

  tasks:
  - name: Include vars file
    include_vars:
      file: vars.yml

  - name: Create CentOS VM
    azure_rm_virtualmachine:
      resource_group: '{{az_resourcegroup}}'
      name: centos01
      vm_size: Standard_DS1_v2
      admin_username: azureuser
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/azureuser/.ssh/authorized_keys
          key_data: '{{key_data}}'
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.5'
        version: latest
  
  - name: install PWSH
    yum:
      name: https://github.com/PowerShell/PowerShell/releases/download/v7.1.0/powershell-7.1.0-1.rhel.7.x86_64.rpm
      state: present