---
- name: Create CentOS VM
  hosts: localhost
  connection: local

  tasks:
  
  - name: Create CentOS VM
    azure_rm_virtualmachine:
      resource_group: '{{az_resourcegroup}}'
      name: '{{az_centos}}'
      vm_size: '{{az_vmsize}}'
      admin_username: azureuser
      open_ports:
        - 22
        - 80
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/azureuser/.ssh/authorized_keys
          key_data: '{{key_data}}'
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.5'
        version: latest
  
  - name: install PWSH
    yum:
      name: https://github.com/PowerShell/PowerShell/releases/download/v7.1.0/powershell-7.1.0-1.rhel.7.x86_64.rpm
      state: present