---
- name: Create Az NSG
  hosts: localhost
  connection: local

  tasks:
  - name: Include vars file
    include_vars:
      file: vars.yml
 
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: '{{az_resourcegroup}}'
      name: '{{az_nsg}}'
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound